Preprocessing Anime dataset from Kaggle

In [1]:
from collections import defaultdict
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel
import matplotlib.pyplot as plt
import re
import string

1. Data preprocessing

1.1 Data Cleaning

In [2]:
# remove unwanted features (columns) from the dataset
anime_df = pd.read_csv("animes.csv")
anime_df.rename(columns={'title': 'name'}, inplace=True)
anime_df.drop(['aired', 'ranked', 'img_url', 'link'], axis=1, inplace=True)

#removing unwanted characters from the anime name strings
def text_cleaning(text):
    text = re.sub(r'&quot;', '', text)
    text  = "".join([char for char in text if char not in string.punctuation])
    text = re.sub(r'.hack//', '', text)
    text = re.sub(r'&#039;', '', text)
    text = re.sub(r'A&#039;s', '', text)
    text = re.sub(r'I&#039;', 'I\'', text)
    text = re.sub(r'&amp;', 'and', text)
    text = re.sub(r'°', '',text)

    return text

anime_df['name'] = anime_df['name'].apply(text_cleaning)
anime_df.head(5)

uid                             name  \
0  28891            Haikyuu Second Season   
1  23273          Shigatsu wa Kimi no Uso   
2  34599                    Made in Abyss   
3   5114  Fullmetal Alchemist Brotherhood   
4  31758   Kizumonogatari III Reiketsuhen   

                                            synopsis  \
0  Following their participation at the Inter-Hig...   
1  Music accompanies the path of the human metron...   
2  The Abyss—a gaping chasm stretching down into ...   
3  "In order for something to be obtained, someth...   
4  After helping revive the legendary vampire Kis...   

                                               genre  episodes  members  \
0  ['Comedy', 'Sports', 'Drama', 'School', 'Shoun...      25.0   489888   
1  ['Drama', 'Music', 'Romance', 'School', 'Shoun...      22.0   995473   
2  ['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...      13.0   581663   
3  ['Action', 'Military', 'Adventure', 'Comedy', ...      64.0  1615084   
4   ['Action', 'Mystery', 'Supernatural', 'Vampire']       1.0   214621   

   popularity  score  
0         141   8.82  
1          28   8.83  
2          98   8.83  
3           4   9.23  
4         502   8.83

In [3]:
anime_df.rename(columns={'uid': 'anime_uid', 'score': 'rating'}, inplace=True)
anime_df.episodes.replace({'Unknown':np.nan},inplace=True)

anime_df.drop_duplicates(subset=['name'], inplace=True)
anime_df.dropna(inplace=True)
anime_df.reset_index(drop=True, inplace=True)

anime_df.head(5)

anime_uid                             name  \
0      28891            Haikyuu Second Season   
1      23273          Shigatsu wa Kimi no Uso   
2      34599                    Made in Abyss   
3       5114  Fullmetal Alchemist Brotherhood   
4      31758   Kizumonogatari III Reiketsuhen   

                                            synopsis  \
0  Following their participation at the Inter-Hig...   
1  Music accompanies the path of the human metron...   
2  The Abyss—a gaping chasm stretching down into ...   
3  "In order for something to be obtained, someth...   
4  After helping revive the legendary vampire Kis...   

                                               genre  episodes  members  \
0  ['Comedy', 'Sports', 'Drama', 'School', 'Shoun...      25.0   489888   
1  ['Drama', 'Music', 'Romance', 'School', 'Shoun...      22.0   995473   
2  ['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...      13.0   581663   
3  ['Action', 'Military', 'Adventure', 'Comedy', ...      64.0  1615084   
4   ['Action', 'Mystery', 'Supernatural', 'Vampire']       1.0   214621   

   popularity  rating  
0         141    8.82  
1          28    8.83  
2          98    8.83  
3           4    9.23  
4         502    8.83

In [4]:
# replace the characters "[]'" with an empty space as the genre column is already of type string
anime_df['genre'] = anime_df['genre'].str.replace("'", "", regex=False)
anime_df['genre'] = anime_df['genre'].str.replace("[", "", regex=False)
anime_df['genre'] = anime_df['genre'].str.replace("]", "", regex=False)

anime_df.head(5)

anime_uid                             name  \
0      28891            Haikyuu Second Season   
1      23273          Shigatsu wa Kimi no Uso   
2      34599                    Made in Abyss   
3       5114  Fullmetal Alchemist Brotherhood   
4      31758   Kizumonogatari III Reiketsuhen   

                                            synopsis  \
0  Following their participation at the Inter-Hig...   
1  Music accompanies the path of the human metron...   
2  The Abyss—a gaping chasm stretching down into ...   
3  "In order for something to be obtained, someth...   
4  After helping revive the legendary vampire Kis...   

                                               genre  episodes  members  \
0             Comedy, Sports, Drama, School, Shounen      25.0   489888   
1             Drama, Music, Romance, School, Shounen      22.0   995473   
2         Sci-Fi, Adventure, Mystery, Drama, Fantasy      13.0   581663   
3  Action, Military, Adventure, Comedy, Drama, Ma...      64.0  1615084   
4             Action, Mystery, Supernatural, Vampire       1.0   214621   

   popularity  rating  
0         141    8.82  
1          28    8.83  
2          98    8.83  
3           4    9.23  
4         502    8.83

In [5]:
normalised_anime_df = anime_df.copy()

normalised_anime_df['members_norm'] = normalised_anime_df['members'] / normalised_anime_df['members'].max()
normalised_anime_df['rating_norm'] = normalised_anime_df['rating'] / normalised_anime_df['rating'].max()
normalised_anime_df['popularity_norm'] = normalised_anime_df['popularity'] / normalised_anime_df['popularity'].max()
normalised_anime_df['episodes_norm'] = normalised_anime_df['episodes'] / normalised_anime_df['episodes'].max()

normalised_anime_df.head()

anime_uid                             name  \
0      28891            Haikyuu Second Season   
1      23273          Shigatsu wa Kimi no Uso   
2      34599                    Made in Abyss   
3       5114  Fullmetal Alchemist Brotherhood   
4      31758   Kizumonogatari III Reiketsuhen   

                                            synopsis  \
0  Following their participation at the Inter-Hig...   
1  Music accompanies the path of the human metron...   
2  The Abyss—a gaping chasm stretching down into ...   
3  "In order for something to be obtained, someth...   
4  After helping revive the legendary vampire Kis...   

                                               genre  episodes  members  \
0             Comedy, Sports, Drama, School, Shounen      25.0   489888   
1             Drama, Music, Romance, School, Shounen      22.0   995473   
2         Sci-Fi, Adventure, Mystery, Drama, Fantasy      13.0   581663   
3  Action, Military, Adventure, Comedy, Drama, Ma...      64.0  1615084   
4             Action, Mystery, Supernatural, Vampire       1.0   214621   

   popularity  rating  members_norm  rating_norm  popularity_norm  \
0         141    8.82      0.261826     0.955580         0.008640   
1          28    8.83      0.532042     0.956663         0.001716   
2          98    8.83      0.310876     0.956663         0.006005   
3           4    9.23      0.863200     1.000000         0.000245   
4         502    8.83      0.114707     0.956663         0.030760   

   episodes_norm  
0       0.008178  
1       0.007197  
2       0.004253  
3       0.020936  
4       0.000327

In [6]:
normalised_anime_df.drop(['members', 'rating', 'popularity', 'episodes'], axis=1, inplace=True)

normalised_anime_df.head()

anime_uid                             name  \
0      28891            Haikyuu Second Season   
1      23273          Shigatsu wa Kimi no Uso   
2      34599                    Made in Abyss   
3       5114  Fullmetal Alchemist Brotherhood   
4      31758   Kizumonogatari III Reiketsuhen   

                                            synopsis  \
0  Following their participation at the Inter-Hig...   
1  Music accompanies the path of the human metron...   
2  The Abyss—a gaping chasm stretching down into ...   
3  "In order for something to be obtained, someth...   
4  After helping revive the legendary vampire Kis...   

                                               genre  members_norm  \
0             Comedy, Sports, Drama, School, Shounen      0.261826   
1             Drama, Music, Romance, School, Shounen      0.532042   
2         Sci-Fi, Adventure, Mystery, Drama, Fantasy      0.310876   
3  Action, Military, Adventure, Comedy, Drama, Ma...      0.863200   
4             Action, Mystery, Supernatural, Vampire      0.114707   

   rating_norm  popularity_norm  episodes_norm  
0     0.955580         0.008640       0.008178  
1     0.956663         0.001716       0.007197  
2     0.956663         0.006005       0.004253  
3     1.000000         0.000245       0.020936  
4     0.956663         0.030760       0.000327

In [7]:
genres_df = anime_df['genre'].str.get_dummies(sep=', ').astype(int)

genres_df.head()

Action  Adventure  Cars  Comedy  Dementia  Demons  Drama  Ecchi  Fantasy  \
0       0          0     0       1         0       0      1      0        0   
1       0          0     0       0         0       0      1      0        0   
2       0          1     0       0         0       0      1      0        1   
3       1          1     0       1         0       0      1      0        1   
4       1          0     0       0         0       0      0      0        0   

   Game  ...  Shounen Ai  Slice of Life  Space  Sports  Super Power  \
0     0  ...           0              0      0       1            0   
1     0  ...           0              0      0       0            0   
2     0  ...           0              0      0       0            0   
3     0  ...           0              0      0       0            0   
4     0  ...           0              0      0       0            0   

   Supernatural  Thriller  Vampire  Yaoi  Yuri  
0             0         0        0     0     0  
1             0         0        0     0     0  
2             0         0        0     0     0  
3             0         0        0     0     0  
4             1         0        1     0     0  

[5 rows x 43 columns]

In [9]:
normalised_anime_df.drop('genre', axis=1, inplace=True)
normalised_anime_df = pd.concat([normalised_anime_df, genres_df], axis=1)

normalised_anime_df.head()

anime_uid                             name  \
0      28891            Haikyuu Second Season   
1      23273          Shigatsu wa Kimi no Uso   
2      34599                    Made in Abyss   
3       5114  Fullmetal Alchemist Brotherhood   
4      31758   Kizumonogatari III Reiketsuhen   

                                            synopsis  members_norm  \
0  Following their participation at the Inter-Hig...      0.261826   
1  Music accompanies the path of the human metron...      0.532042   
2  The Abyss—a gaping chasm stretching down into ...      0.310876   
3  "In order for something to be obtained, someth...      0.863200   
4  After helping revive the legendary vampire Kis...      0.114707   

   rating_norm  popularity_norm  episodes_norm  Action  Adventure  Cars  ...  \
0     0.955580         0.008640       0.008178       0          0     0  ...   
1     0.956663         0.001716       0.007197       0          0     0  ...   
2     0.956663         0.006005       0.004253       0          1     0  ...   
3     1.000000         0.000245       0.020936       1          1     0  ...   
4     0.956663         0.030760       0.000327       1          0     0  ...   

   Shounen Ai  Slice of Life  Space  Sports  Super Power  Supernatural  \
0           0              0      0       1            0             0   
1           0              0      0       0            0             0   
2           0              0      0       0            0             0   
3           0              0      0       0            0             0   
4           0              0      0       0            0             1   

   Thriller  Vampire  Yaoi  Yuri  
0         0        0     0     0  
1         0        0     0     0  
2         0        0     0     0  
3         0        0     0     0  
4         0        1     0     0  

[5 rows x 93 columns]

In [11]:
features = ['members_norm', 'rating_norm', 'popularity_norm', 'episodes_norm'] + genres_df.columns.tolist()

cosine_sim = cosine_similarity(normalised_anime_df[features], normalised_anime_df[features])

print(cosine_sim)

[[1.         0.63605328 0.27240971 ... 0.32548184 0.14530463 0.62804101]
 [0.63605328 1.         0.27741747 ... 0.09198012 0.1449694  0.62368293]
 [0.27240971 0.27741747 1.         ... 0.09195706 0.14540291 0.25869162]
 ...
 [0.32548184 0.09198012 0.09195706 ... 1.         0.16045813 0.55367089]
 [0.14530463 0.1449694  0.14540291 ... 0.16045813 1.         0.12681484]
 [0.62804101 0.62368293 0.25869162 ... 0.55367089 0.12681484 1.        ]]


In [12]:
indices = pd.Series(anime_df.index, index=anime_df['name']).drop_duplicates()

In [13]:
def get_recommendations(title, cosine_sim=cosine_sim, anime_df=anime_df, indices=indices):
    # Get the index of the anime that matches the title
    idx = indices[title]

    # Get the pairwise cosine similarity scores for all anime with that index
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the anime based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the top 10 most similar anime
    sim_scores = sim_scores[1:11]

    # Get the titles of the top 10 most similar anime
    anime_indices = [i[0] for i in sim_scores]
    anime_titles = anime_df['name'].iloc[anime_indices].values.tolist()

    return anime_titles

In [17]:
get_recommendations('Death Note')

['Death Note Rewrite',
 'Mirai Nikki',
 'B The Beginning',
 'Higurashi no Naku Koro ni Kai',
 'Mousou Dairinin',
 'Zankyou no Terror',
 'Higurashi no Naku Koro ni Rei',
 'Mouryou no Hako',
 'Imawa no Kuni no Alice OVA',
 'Jigoku Shoujo Mitsuganae']

In [ ]:
user_ratings_df = pd.read_csv("reviews.csv")
user_ratings_df.head(5)

1.2 Merging the datasets

In [ ]:
# remove unwanted columns
user_ratings_df.drop(['uid', 'link'], axis=1, inplace=True)
user_ratings_df.head(5)

In [ ]:
# change profile names into unique IDs (i.e. integers)
user_ratings_df.profile = pd.factorize(user_ratings_df.profile)[0]
user_ratings_df.rename(columns={'profile': 'user_id'}, inplace=True)
user_ratings_df.head(10)

In [ ]:
merged_anime_reviews_df = pd.merge(anime_df, user_ratings_df, on='anime_uid')
merged_anime_reviews_df.rename(columns={'score_x':'avg_rating', 'text': 'review_text'},inplace=True)

merged_anime_reviews_df.drop('review_text', axis=1, inplace=True)

merged_anime_reviews_df.head()

Categorical encoding -> Separating genres into their own respective column

In [ ]:
# replace the characters "[]'" with an empty space as the genre column is already of type string
# merged_anime_reviews_df['genre'] = merged_anime_reviews_df['genre'].str.replace("'", "", regex=False)
# merged_anime_reviews_df['genre'] = merged_anime_reviews_df['genre'].str.replace("[", "", regex=False)
# merged_anime_reviews_df['genre'] = merged_anime_reviews_df['genre'].str.replace("]", "", regex=False)

# merged_anime_reviews_df.head(5)

Clean data -> drop duplicates + NaN values

In [ ]:
# merged_anime_reviews_df.drop_duplicates(inplace=True)
# merged_anime_reviews_df.dropna(inplace=True)